apiVersion: apps/v1
kind: Deployment
metadata:
  name: adder-deployment
  labels:
    app: adder
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adder
  template:
    metadata:
      labels:
        app: adder
    spec:
      containers:
      - name: adder
        image: "registry.cn-hangzhou.aliyuncs.com/maycur/adder:V2"
        ports:
        - containerPort: 3333
          name: http
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
        - name: aliyun-docker-regcred
