apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: adder
        image: "wsy/config-server:V1"
        ports:
        - containerPort: 4444
        imagePullPolicy: IfNotPresent
