apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-test
  labels:
    app: config-server-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server-test
  template:
    metadata:
      labels:
        app: config-server-test
    spec:
      volumes:
        - name: config-files-storage
          hostPath:
            # directory location on host
            path: /root/git/spring-cloud-config-demo
            # this field is optional
            type: Directory
      imagePullSecrets:
        - name: aliyun-docker-regcred
      nodeSelector:
        config.files.prepared: "true"
      containers:
        - name: config-server-test
          image: "registry.cn-hangzhou.aliyuncs.com/maycur/config-server-test:V1"
          ports:
            - containerPort: 4444
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "/usr/share/config-files"
              name: config-files-storage

