apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      volumes:
        - name: config-files-storage
          persistentVolumeClaim:
           claimName: config-files-claim
      containers:
          imagePullSecrets:
          - name: aliyun-docker-regcred
        - name: config-server
          image: "config-server:V1"
          ports:
            - containerPort: 4444
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "/usr/share/config-files"
              name: config-files-storage

