kind: Service
apiVersion: v1
metadata:
  name: config-server-test
  labels:
    app: config-server-test
spec:
  selector:
    app: config-server-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4444
  type: NodePort
