apiVersion: apps/v1
kind: Deployment
metadata:
  name: facade
  labels:
    app: facade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facade
  template:
    metadata:
      labels:
        app: facade
    spec:
      containers:
      - name: facade
        image: "registry.cn-hangzhou.aliyuncs.com/maycur/facade:V2"
        ports:
          - containerPort: 2222
            name: http
        imagePullPolicy: Always
      imagePullSecrets:
      - name: aliyun-docker-regcred
