version: "2"
services:
  consul1:
    image: "progrium/consul:latest"
    container_name: "consul1"
    hostname: "consul1"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    command: "-server -bootstrap-expect 1 -ui-dir /ui"
  adder:
    image: wsy/adder
    ports:
      - "3333:3333"
    links:
      - consul1
    environment:
      WAIT_FOR_HOSTS: consul1:8500
    depends_on:
      - consul1

