discovery:
  image: "progrium/consul:latest"
  container_name: "discovery-consul"
  hostname: "discovery-consul"
  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:53"
  command: "-server -bootstrap -ui-dir /ui"
config:
  image: "wsy/config-server"
  ports:
   - "8888:8888"
  links:
   - discovery
adder:
  image: wsy/adder
  ports:
   - "3333:3333"
  links:
   - discovery
facade:
  image: wsy/facade
  ports:
   - "2222:2222"
  links:
   - discovery
   - adder
   - config
