server:
  port: 3333

spring:
  application:
    name: adder
  cloud:
    consul:
      host: discovery
      port: 8500
      discovery:
        ipAddress: localhost
        port: 3333
        preferIpAddress: true
        healthCheckPath: /health
        healthCheckInterval: 15s
        instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}


