spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangsenyuan/spring-cloud-config-demo.git
          searchPaths: '{profile}'
          cloneOnStart: true
allowed:
  applications:
    - facade
  urls:
    - refresh
    - error
