spring:
  cloud:
    config:
      server:
        git:
          uri: /usr/share/config-files
          searchPaths: '{profile}'
          cloneOnStart: true
allowed:
  applications:
    - facade
    - application
  urls:
    - refresh
    - error
server:
  port: 4444
management:
  port: 4444
